// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAE_sEmLM_evInDHPk2i-cYPJo2h6YQeE',
    appId: '1:73249083573:web:1cb08c2fea6e16a471eefc',
    messagingSenderId: '73249083573',
    projectId: 'jobready-flutter-app',
    authDomain: 'jobready-flutter-app.firebaseapp.com',
    storageBucket: 'jobready-flutter-app.firebasestorage.app',
    measurementId: 'G-J1ZV3CE95Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3R8epWy6NNPz8fyMQhoPfRAHpyWWc1v0',
    appId: '1:73249083573:android:bd1fffd15303954271eefc',
    messagingSenderId: '73249083573',
    projectId: 'jobready-flutter-app',
    storageBucket: 'jobready-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5alD6k-elU8rIvv3BufnZo0IU7nWuJSQ',
    appId: '1:73249083573:ios:9be48ba26f7e30a071eefc',
    messagingSenderId: '73249083573',
    projectId: 'jobready-flutter-app',
    storageBucket: 'jobready-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.jobready',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5alD6k-elU8rIvv3BufnZo0IU7nWuJSQ',
    appId: '1:73249083573:ios:9be48ba26f7e30a071eefc',
    messagingSenderId: '73249083573',
    projectId: 'jobready-flutter-app',
    storageBucket: 'jobready-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.jobready',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAE_sEmLM_evInDHPk2i-cYPJo2h6YQeE',
    appId: '1:73249083573:web:e04fe6dde521fdca71eefc',
    messagingSenderId: '73249083573',
    projectId: 'jobready-flutter-app',
    authDomain: 'jobready-flutter-app.firebaseapp.com',
    storageBucket: 'jobready-flutter-app.firebasestorage.app',
    measurementId: 'G-Y0KS8TDVMY',
  );
}
